#!/bin/bash


export GIT_COMMIT=$(git rev-list -1 HEAD)
export KEES_CONFIG="./kees.yml"


case $1 in
  build)
    output="controller"
    if [ "$2" == "pi" ]; then
      export GOARCH=arm
      export GOARM=5
      export GOOS=linux
      output="${output}-pi"
    fi

    gofmt -w .
    go build -ldflags "-X kees/controller/constants.GitCommit=$GIT_COMMIT" -o release/$output
    ;;

  run)
    ./release/controller
    ;;

  again)
    ./k build
    if [ $? -ne 0 ]; then
      echo "Build failed"
      exit 1
    fi
    ./k run
    ;;

  *)
    echo "Unrecognized kees Command"
    ;;
esac
