#!/bin/bash


export GIT_COMMIT=$(git rev-list -1 HEAD)
export KEES_CONFIG="./kees.yml"

MIGRATION_PATH="db/migrations"


case $1 in
  build)
    gofmt -w .
    go build -ldflags "-X kees/server/constants.GitCommit=$GIT_COMMIT"
    ;;

  migration)
    MIGRATION_FILE="$(date +%s_%Y-%m-%d_%H-%M-%S)_${2}.sql"
    MIGRATION="${MIGRATION_PATH}/${MIGRATION_FILE}"
    echo "Creating migration file ${MIGRATION}"
    printf "\n\n\nINSERT INTO migrations (name, migrated_at)\n  VALUES (\"%s\", strftime('%%s', \"now\"));" $MIGRATION_FILE > $MIGRATION
    ;;

  migrate)
    for migration in `ls db/migrations/*.sql`; do
      echo $migration
      sqlite3 db/kees.db < $migration
    done

    ;;

  run)
    ./server
    ;;

  again)
    ./k build
    if [ $? -ne 0 ]; then
      echo "Build failed"
      exit 1
    fi
    ./k run
    ;;

  *)
    echo "Unrecognized kees Command"
    ;;
esac
